keyExchangerate: ${KEY_EXCAPI}
keyAbstractapi: ${KEY_ABSAPI}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_first_base
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

