keys:
  keyExchangerate: ${KEY_EXCAPI}
  keyAbstractapi: ${KEY_ABSAPI}
  keyOpenexchangerates: ${KEY_OEXAPI}
urls:
  urlExchangerate: ${URL_EXCAPI}
  urlAbstractapi: ${URL_ABSAPI}
  urlOpenexchangerates: ${URL_OEXAPI}
spring:
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://db-service:5432/my_first_base
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true