apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: my_first_base
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432