name: CICD
on:
  push:
    branches: [master]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build image
        run: docker build -t evgeniykulpinov/docker-spring-boot-postgres:latest .

      - name: Push image
        run: docker push evgeniykulpinov/docker-spring-boot-postgres:latest

      - name: Copy docker-compose.yaml via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.DEPLOY_USERNAME }}"
          overwrite: true
  deploy_app:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build_and_push ]
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/${{ secrets.DEPLOY_USERNAME }}
            sudo docker-compose down
            sudo docker rmi evgeniykulpinov/docker-spring-boot-postgres:latest
            sudo docker pull evgeniykulpinov/docker-spring-boot-postgres:latest
            sudo docker-compose up --force-recreate -d
